/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CircleRouteImport } from './routes/circle'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as FavoritesRouteImport } from './routes/favorites'
import { Route as GarageRouteImport } from './routes/garage'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SearchRouteImport } from './routes/search'
import { Route as BookingsIndexRouteImport } from './routes/bookings/index'
import { Route as BookingsIdRouteImport } from './routes/bookings/$id'
import { Route as CarsSlugRouteImport } from './routes/cars/$slug'
import { Route as ReserveSlugRouteImport } from './routes/reserve.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CircleRoute = CircleRouteImport.update({
  id: '/circle',
  path: '/circle',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesRoute = FavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const GarageRoute = GarageRouteImport.update({
  id: '/garage',
  path: '/garage',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIndexRoute = BookingsIndexRouteImport.update({
  id: '/bookings/',
  path: '/bookings/',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsIdRoute = BookingsIdRouteImport.update({
  id: '/bookings/$id',
  path: '/bookings/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CarsSlugRoute = CarsSlugRouteImport.update({
  id: '/cars/$slug',
  path: '/cars/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ReserveSlugRoute = ReserveSlugRouteImport.update({
  id: '/reserve/$slug',
  path: '/reserve/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/reserve/$slug': typeof ReserveSlugRoute
  '/bookings/': typeof BookingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/reserve/$slug': typeof ReserveSlugRoute
  '/bookings': typeof BookingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/circle': typeof CircleRoute
  '/explore': typeof ExploreRoute
  '/favorites': typeof FavoritesRoute
  '/garage': typeof GarageRoute
  '/login': typeof LoginRoute
  '/search': typeof SearchRoute
  '/bookings/$id': typeof BookingsIdRoute
  '/cars/$slug': typeof CarsSlugRoute
  '/reserve/$slug': typeof ReserveSlugRoute
  '/bookings/': typeof BookingsIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/circle'
    | '/explore'
    | '/favorites'
    | '/garage'
    | '/login'
    | '/search'
    | '/bookings/$id'
    | '/cars/$slug'
    | '/reserve/$slug'
    | '/bookings/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/circle'
    | '/explore'
    | '/favorites'
    | '/garage'
    | '/login'
    | '/search'
    | '/bookings/$id'
    | '/cars/$slug'
    | '/reserve/$slug'
    | '/bookings'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/circle'
    | '/explore'
    | '/favorites'
    | '/garage'
    | '/login'
    | '/search'
    | '/bookings/$id'
    | '/cars/$slug'
    | '/reserve/$slug'
    | '/bookings/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CircleRoute: typeof CircleRoute
  ExploreRoute: typeof ExploreRoute
  FavoritesRoute: typeof FavoritesRoute
  GarageRoute: typeof GarageRoute
  LoginRoute: typeof LoginRoute
  SearchRoute: typeof SearchRoute
  BookingsIdRoute: typeof BookingsIdRoute
  CarsSlugRoute: typeof CarsSlugRoute
  ReserveSlugRoute: typeof ReserveSlugRoute
  BookingsIndexRoute: typeof BookingsIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/circle': {
      id: '/circle'
      path: '/circle'
      fullPath: '/circle'
      preLoaderRoute: typeof CircleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites': {
      id: '/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof FavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garage': {
      id: '/garage'
      path: '/garage'
      fullPath: '/garage'
      preLoaderRoute: typeof GarageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/': {
      id: '/bookings/'
      path: '/bookings'
      fullPath: '/bookings/'
      preLoaderRoute: typeof BookingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings/$id': {
      id: '/bookings/$id'
      path: '/bookings/$id'
      fullPath: '/bookings/$id'
      preLoaderRoute: typeof BookingsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cars/$slug': {
      id: '/cars/$slug'
      path: '/cars/$slug'
      fullPath: '/cars/$slug'
      preLoaderRoute: typeof CarsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reserve/$slug': {
      id: '/reserve/$slug'
      path: '/reserve/$slug'
      fullPath: '/reserve/$slug'
      preLoaderRoute: typeof ReserveSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CircleRoute: CircleRoute,
  ExploreRoute: ExploreRoute,
  FavoritesRoute: FavoritesRoute,
  GarageRoute: GarageRoute,
  LoginRoute: LoginRoute,
  SearchRoute: SearchRoute,
  BookingsIdRoute: BookingsIdRoute,
  CarsSlugRoute: CarsSlugRoute,
  ReserveSlugRoute: ReserveSlugRoute,
  BookingsIndexRoute: BookingsIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
